### ISSUE TITLE
Transit duration as input

### ISSUE THREAD

**Issue by martindevora** [MNGuenther/allesfitter#14]
Hi. I'm beginning to use allesfitter for transit fitting. I was wondering why there is no input parameter for the transit duration. Would you please help me with this? I'm using the light curve where I previously found a possible transit candidate with X duration, but a nested sampling run is returning very big uncertainties and the transit duration expands from X to 2*X (the light curve shows a little bit of variability before the transit). I would like to know how could I tell allesfitter that I know an estimation of the duration so the model can adjust better to it.

I'm sorry if I'm misunderstanding something but I'm very new with transit modeling.
Kind regards.

**Comment by tdaylan** [comment]
Hi,

Allesfitter’s light curve parametrization does not directly include the transit duration. Instead, it has two relevant parameters:

i) Sum of the radii of the transiting object and the background object divided by the semi-major axis of the orbit. For an exoplanet transit, this would be the sum of the planetary radius and the stellar radius divided by the semi-major axis. This is called rsuma in the allesfitter name space.

ii) The cosine of the inclination angle (cosi in allesfitter).

The total transit duration depends on the orbital period and eccentricity as well as i) and ii) (See Winn2010, Eq14). Therefore, if you have an estimate and/or assumption about the transit duration and the inclination angle, you can turn that into an initial guess or prior for i) and ii).

Best,
Tansu

**Comment by martindevora** [comment]
Thank you for your answer and for pointing to the right equation. The problem is that I don't have an estimation about the inclination angle but I will try to get an initial guess from my data. To me, this issue is solved.
Regards.

**Comment by MNGuenther** [comment]
Hi,
Since it's a transiting exoplanet, the inclination will be close to 90 degree, i.e. cos(i) will be close to 0. You can either use MCMC and set the initial guess of cos(i) to 0 with uniform priors from 0 to 0.1 (for example). Or you can use Nested Sampling with uniform priors from 0 to 0.1 (for example). Both will work!
Hope all will go well, and thanks for using allesfitter 👍 
Best
Max

**Comment by martindevora** [comment]
"To get even better guesses or priors, you can also "reverse engineer" the cos(i) range by using the equation Tansu pointed you to." That's what I will do! Thank you very much for delivering such a nice modeling tool : )
