### ISSUE TITLE
GUI (Jupyter-notebook) in server

### ISSUE THREAD

**Issue by TakuNishiumi** [MNGuenther/allesfitter#15]
Hello.
I just started to use allesfitter.

I runs jupyter-notebook in our server and open the notebook in my laptop's browser.
When I run the `GUI.ipynb` in server and open it in my laptop's browser, I couldn't select directory because tk() needs browser in the server. 
Although I installed a browser in server, the directory-GUI was sent via X-window system. This is very slow.
Do you have any ideas to solve this?

**Comment by MNGuenther** [comment]
Hi,

Thanks for reaching out. The GUI is just a fancy gimmick, but not really necessary. So there are a few ways to solve this:

(i) use the GUI on your laptop and once you created the params.csv and settings.csv files, just copy/synchronize your "allesfit" directory over to your servers. Then, on your servers, run allesfitter via the scripts. See: https://www.allesfitter.com/tutorials/tutorial-1b-crash-course-without-gui

(ii) don't use the GUI at all, but set up all files in any text or csv editor on your servers, and then run allesfitter via the scripts. Again, see: https://www.allesfitter.com/tutorials/tutorial-1b-crash-course-without-gui

(iii) connect to your servers via a third-party software that allows X-windows; many universities support something like Teamviewer.

Hope this helps!
Max

**Comment by TakuNishiumi** [comment]
Dear @MNGuenther,

Thank you very much.
Number (i) is suitable for me.
I will try it.

Regards,
@TakuNishiumi
