### ISSUE TITLE
Select final ns_fit x axis limit of phase & T - T0 plots

### ISSUE THREAD

**Issue by martindevora** [MNGuenther/allesfitter#17]
I would like to know whether we can select the x_lims of the phase and T - T0 plots of the final ns_fit pdf. For instance, we run a fit where we have selected a 'fast_fit_width=0.15'. The plots are however plotting the entire phase and -4 to 4 hours in the T-T0 plot. Image provided as an example:

![image](https://user-images.githubusercontent.com/62331042/97089093-59bf9800-162d-11eb-8f0d-ca3229b7b154.png)

We would like to stretch both plots to the size of our data somehow. Is this possible through the usage of some config params? For instance, given that we can use the fast_fit_width I'd expect some way to focus on the proper range in both plots.

Kind regards and thank you in advance.

**Comment by MNGuenther** [comment]
Absolutely! You can use the allesclass to make custom plots:

**Comment by martindevora** [comment]
Amazing. Thank you for pointing to the right spot and sorry for asking about something that is very well documented.
