### ISSUE TITLE
Fitting offset + gp for RVs

### ISSUE THREAD

**Issue by jvines** [MNGuenther/allesfitter#20]
Hi,

Is it possible to fit both an offset and a GP to the RVs?

Cheers,

Jose V.

**Comment by MNGuenther** [comment]
Hi Jose,
Yes! But first I would check -- is it needed? The GP can handle small offsets on its own. But it wouldn't handle the full systemic offset of non-normalized RVs.
-

**Comment by jvines** [comment]
In that case, yes, I need it! I haven't normalized them at all! How can I fit for the offset and GP??

**Comment by MNGuenther** [comment]
See above (I just finished editing, GitHub sent my first sentence by accident when I just wanted to hit enter for a new paragraph)

**Comment by jvines** [comment]
Thank you very much!

Also, real quick, I just noticed that in the `ns_derived_latex_table.txt` the companion density units appear as `\$rho_\mathrm{b}$ (cgs)` instead of  `$\rho_\mathrm{b}$ (cgs)`

**Comment by MNGuenther** [comment]
Cheers, just fixed the typo. Will come with the next version!
