### ISSUE TITLE
wotan is required but it isn't specified in the documentation

### ISSUE THREAD

**Issue by jvines** [MNGuenther/allesfitter#27]
Exactly the title. I'd suggest you add wotan in the required packages, otherwise, you can't import allesfitter

**Comment by MNGuenther** [comment]
Thanks, @jvines. Wotan (and transitleastsquares) are actually not required. They are only used if you want to do transit searches or advanced TTV analyses with allesfitter. I have try/excepted all imports and dependencies, and released the new v1.1.6. That should solve it for users who don't have wotan (or transitleastsquares) installed. Please feel free to reopen this if your issue persists after updating.
