### ISSUE TITLE
[Bug] Missing last companion Total Transit Duration

### ISSUE THREAD

**Issue by martindevora** [MNGuenther/allesfitter#36]
Hi,
I was able to generate the results directory for a 5-candidates system. I found out a very weird system, which might probably point to False candidates. I wanted to do some checks in the derived data when I realised that the last companion was missing the Total and Full Transit Duration from the `ns_derived_table` files (latex tables and csv file). I'm attaching the entire allesfitter working directory for you to be able to debug the case.

The link to the allesfitter dir (the file is too large to be attached here): https://drive.google.com/file/d/1AQO_MTCutPOQjlfOHgqfFMYrdeElv0O0/view?usp=sharing

I'm running allesfitter **1.2.2**.

Regards.

**Comment by martindevora** [comment]
I opened the derived pickle file. The values 'SOI_5_T_tra_tot' and 'SOI_5_T_tra_full' contain a first NaN value at the index = 0. Therefore, the piece of code from `deriver.derive` doing this:
```
ind_good = []
    for i,name in enumerate(names):
        if (name in derived_samples) and isinstance(derived_samples[name], np.ndarray) and not any(np.isnan(derived_samples[name])) and not all(np.array(derived_samples[name])==0):
            ind_good.append(i)
```
seems to be filtering the durations for this companion. I guess this is intended, but I'm wondering what is the cause of having NaN values and why we would ignore this derived parameter when only having one NaN value out of more than 30,000 as my current scenario.

Kind regards,
Martín.

**Comment by martindevora** [comment]
Hi again here in some additional thread : )

I don't remember which one, but this happened again two weeks ago with some other system I was exploring too. It seemed that the last candidate (as happened in the case I uploaded to this issue) was missing the duration due to the same problem (first value from the samples is NaN). So I believe this is not an isolated problem. I must recognize that I'm trying to fit very shallow transits, but still, I'm providing the initial priors for the duration.

PS: Good luck with your new position in the ESA!

**Comment by MNGuenther** [comment]
Hi @martindevora,

Ok, twice is too often :) In v1.2.7 (pip-installable by this evening) I have replaced the `not any()` with an `not all()`, and am using np.nanpercentile functions to allow computing the desired medians and lower/upper limits. I tested it on your example above and it ran well. 

(I am still not happy that there is a NaN in the first position of the samples, but it is hard to diagnose why that is.)

Please feel free to reopen this if you find a continuing/related issue in v1.2.7 and beyond.
