### ISSUE TITLE
Double Lined (SB2) Binaries in Allesfitter

### ISSUE THREAD

**Issue by JackActon96** [MNGuenther/allesfitter#37]
Is there a way to fit double lined binaries within allesfitter, and if so what extra parameters/settings are needed to do this - apologies if this is in the documentation, but I couldn't find anything.

**Comment by MNGuenther** [comment]
Hi @JackActon96! Yes, this is readily possible and super easy. All you need to do is save the secondary's RV series as a separate file. So you would have, for example, "HARPS_Primary.csv" and "HARPS_Secondary.csv". I have made this more visible now in the [website's tutorials tabs](https://www.allesfitter.com/tutorials/7-double-lined-sb2-binaries) and with an [explicit GitHub example.](https://github.com/MNGuenther/allesfitter/tree/master/tutorials/07_double_lined_sb2_binaries/allesdir). Hope this helps and happy fitting!

(Sorry for the delay, this fell through the cracks while I was moving from MIT to ESA.)
