### ISSUE TITLE
Typo in ttvs plot

### ISSUE THREAD

**Issue by martindevora** [MNGuenther/allesfitter#44]
I'm finding that "Tranist Nr." instead of "Transit Nr." appears as X label in the ttv results report. Please correct this whenever you find it suitable.
[ttv_results_SOI_1.pdf](https://github.com/MNGuenther/allesfitter/files/7532296/ttv_results_SOI_1.pdf)

Regards and thanks again.

**Comment by MNGuenther** [comment]
Thanks Martin, fixed and updated on GitHub. I will push this to PyPi with any future release of v1.2.9.
