### ISSUE TITLE
TTVs preparation plots with gaps

### ISSUE THREAD

**Issue by martindevora** [MNGuenther/allesfitter#46]
Hi,

when running the allesfitter ttvs module for curves with long gaps (like TESS ones for very separated sectors) the plots of the transits within the curve are very complicated to be assessed: less x-axis values and huge long horizontal monolithic plot. I don't know what can of improvements you could do (maybe splitting the document with n plots -one per dataset without gaps-), but just noticed that it is complicated to be read. I attach an example.
![ttv_preparation_SOI_2](https://user-images.githubusercontent.com/62331042/141816416-46e80a72-c4af-4746-8856-dedfbbc1f232.jpg)

Regards.

**Comment by MNGuenther** [comment]
Ah I see. We can probably just replace this plot with either the tessplot() or the monthplot() function from allesfitter.plotting. Will look into it.

**Comment by MNGuenther** [comment]
I have added the option to tailor this plot now in versions >=1.2.9 (freshly pushed to GitHub and PyPI). You can now use any of the following options:
> allesfitter.prepare_ttv_fit('allesfit_with_ttvs')
> allesfitter.prepare_ttv_fit('allesfit_with_ttvs', style='fullplot') #same as before, this is the default
> allesfitter.prepare_ttv_fit('allesfit_with_ttvs', style='brokenplot')
> allesfitter.prepare_ttv_fit('allesfit_with_ttvs', style='chunkplot')
> allesfitter.prepare_ttv_fit('allesfit_with_ttvs', style='monthplot')
> allesfitter.prepare_ttv_fit('allesfit_with_ttvs', style='tessplot')
All of these are explained and explored in the new tutorial_17 python script and Jupyter notebook.
