### ISSUE TITLE
TTVs transit numbers differ

### ISSUE THREAD

**Issue by martindevora** [MNGuenther/allesfitter#47]
Hi,
while trying out the TTVs module I realized about something. When I open the ttpvs-per-transit plot of my second candidate, the transit numbering differs to the TTVs initial guess transit numbering. See attached image:
![image](https://user-images.githubusercontent.com/62331042/141817012-1470e81d-fe6f-4b50-ac11-400e4fca2463.png)
You can see that transit 5 data is skipped in the initial_guess plot (right) and then its transit 5 matches the ttv_preparation transit 6. I guess this is somehow related to the transit lacking some data, but the point is that the numbering should be kept. I don't know whether this is also related to the transit fit missing the model at all (I only see the baseline).

In addition, this also would be affecting the final TTVs plot. See next attached image:
![image](https://user-images.githubusercontent.com/62331042/141818195-a801e283-11ec-4bb4-8cd9-15de7446ab04.png)
You can see that the transit 6 ttv from the final fit doesn't match the 6th point in the graph, but the 7th. I'm guessing that the transit numbering is matching the ttvs_preparation stage one instead of the transit numbering from the fit. Hence the mess. If this was the case, I don't know where the transit 5 data was obtained either. 

Sorry if it sounds chaotic, but these are only some previous findings I've been getting. For clarity purposes, I'm also attaching my entire allesfitter working dir: https://drive.google.com/file/d/18t--3SnycEIjBxgYkNKr5S8uYiGu1uc9/view?usp=sharing

**Comment by MNGuenther** [comment]
Hm, I think I see what's happening here. Thanks for sharing the directory. Will look into it!

**Comment by MNGuenther** [comment]
Hi @martindevora, I think this should be fixed now that I updated the modules. I lost access to your Google Drive folder from above unfortunately. If this re-occurs or persists, please feel free to open this again!
