### ISSUE TITLE
[Question] ns_output errors calculated from median

### ISSUE THREAD

**Issue by martindevora** [MNGuenther/allesfitter#48]
Hi,

I observed that the final uncertainties provided by Allesfitter are the values from the median of the normal distributions. Is this the standard approach for all the bayesian models? I was observing the typical corner plots and the `allesfitter.ns_output` function and thought that we are leaving half the probabilities out of the uncertainty by using the median. 

I don't want to ask for a change in allesfitter to use another different percentile, but would it be dumb to ask for a parameter in allesfitter.ns_output where we could select the percentile to be used for the errors? I ran out into a case where a ground observation campaign was completely missing the target real ephemerides because the propagated error was unproperly estimated based on the allesfitter results uncertainties and thought that it might be something to be improved. Of course I could just use two or three times the allesfitter uncertainties values, but I'd like better to stick to some statistical threshold given by a higher percentile than the median.

Again, thank you very much for your help. Hope everything goes fine in the ESA : P

Kind regards.

**Comment by martindevora** [comment]
Of course, if you are overloaded or find it a trivial change, I offer myself to send you a merge request with the changes so you just need to review and approve them.

**Comment by MNGuenther** [comment]
Hi Martin :) 

Indeed, it is common practice that any Tables report the 16, 50, and 84 percentile for any MCMC or NS fitted posterior distributions. That is a good guideline but in exceptional cases (e.g. skewed or multimodal posterior distributions) it can be misleading. So it's always important to include the posterior distributions directly (e.g. in corner plots). 

You can readily use the allesclass to get the full posterior distribution: https://www.allesfitter.com/allesclass/retriving-data-and-models

I noticed the documentation is very sparse on this (and focuses mostly on the plotting). The relevant functions for you would be:

```
#::: initialize the allesclass
alles = allesfitter.allesclass(datadir)

alles.posterior_samples(inst, key) # all weighted posterior_samples as an N-dimensional array
alles.posterior_params(inst, key)   # all weighted posterior_samples as a dictionary
alles.posterior_params_median(inst, key)  # the 50 percentile values as a dictionary
alles.posterior_params_ll(inst, key)  #the 16 percentile values as a dictionary
alles.posterior_params_ul(inst, key)  #the 84 percentile values as a dictionary
```

The MCMC functions directly include `alles.posterior_samples_at_maximum_likelihood(inst, key)` and `alles.posterior_params_at_maximum_likelihood(inst, key)` but I haven't had time to write this for NS yet. 

In any case, the posterior distribution you get out of this (be it for MCMC or NS) will enable you to propagate all aspects forward for observation scheduling! 

Out of curiosity, I am a bit puzzled to hear the problem arose from using the 16, 50, 84 percentiles of the period and epoch. Usually, given that we shift the epoch into the data center, epoch and period should be uncorrelated (and thus Gaussian). If you see they are strongly correlated, it might come from some very old data that "pulls" the epoch off the true center. Let's assume you have a very old Coralie RV data and brand-new TESS photometry data. Then you can always give the settings.csv file the key:
inst_for_shift_epoch,TESS
for example, if you only want TESS to dictate where the epoch is defined. As old Coralie RV data won't influence the epoch and period much, this should ensure that their posterior distributions are uncorrelated.

Hope this helps!

**Comment by martindevora** [comment]
Hi Max, thanks for such a detailed answer!

Our main problem, I believe, was that percentiles 16th and 84th weren't enough for the error propagation of the period after more than one year for our given candidate. Therefore, where the propagated error was 3.5 hours bottom and above (for 16th and 84th percentiles), it should have been a little more than 8 hours at least for us to be able to catch the transits. I was guessing that one of the main reasons was that the transit was very shallow and probably the gaussian distribution got wider, but I'm not sure about that statement.

Anyhow, I will stick to more conservative percentiles for observations scheduling thanks to the allesfitter.posterior_params method. Thank you so much again.

Kind regards.
