### ISSUE TITLE
Small bug creating keys for baseline offsets (RV)

### ISSUE THREAD

**Issue by mycojo** [MNGuenther/allesfitter#50]
Was trying to set RV offsets for an instrument and kept getting a key error, the key being created was using 'flux' instead of 'rv' in the string. Here's the error message: 
<img width="1139" alt="Screen Shot 2022-03-13 at 5 24 35 PM" src="https://user-images.githubusercontent.com/98989560/158093911-7ef7b905-593d-45e8-bf59-2ad434f02066.png">
Did some poking around, looks like in lines 284, 288, and 289 of the 3rd section of Parameters, the string being created was defaulting to using 'flux' instead of looking at the key ('flux' or 'rv'). Here's what they looked like originally:
<img width="991" alt="Screen Shot 2022-03-13 at 10 28 07 PM" src="https://user-images.githubusercontent.com/98989560/158094990-59caa53d-f04d-428a-94e5-987d7be06d97.png">
It was an easy fix, I switched it to match the formatting of the above parameters and it works fine for me now. Here's what it looked like when I got it working:
<img width="1012" alt="Screen Shot 2022-03-13 at 10 29 29 PM" src="https://user-images.githubusercontent.com/98989560/158095095-6241bfe2-1ec5-48f5-9909-b32d29ada965.png">
Not sure if this is just something I've experienced or if this is a wider issue, just letting you know!

**Comment by MNGuenther** [comment]
Ah fantastic, thanks a lot for finding this bug and already providing the solution, @mycojo! Will be fixed in the next GitHub push and pip-release asap!
