### ISSUE TITLE
Installation error in 'ellc' package

### ISSUE THREAD

**Issue by sam687** [MNGuenther/allesfitter#63]
Hi,
I am getting the following error while installing 'allesfitter' inside a conda environment in Ubuntu 20.04.5. It shows an error while installing ellc with pip. does anyone have any solution? thank you.

      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize IntelFCompiler
      Could not locate executable ifort
      Could not locate executable ifc
      customize LaheyFCompiler
      Could not locate executable lf95
      customize PGroupFCompiler
      Could not locate executable pgfortran
      customize NVHPCFCompiler
      Could not locate executable nvfortran
      customize AbsoftFCompiler
      Could not locate executable f90
      Could not locate executable f77
      customize NAGFCompiler
      customize VastFCompiler
      customize CompaqFCompiler
      Could not locate executable fort
      customize IntelItaniumFCompiler
      Could not locate executable efort
      Could not locate executable efc
      customize IntelEM64TFCompiler
      customize GnuFCompiler
      Could not locate executable g77
      customize G95FCompiler
      Could not locate executable g95
      customize PathScaleFCompiler
      Could not locate executable pathf95
      customize NAGFORCompiler
      Could not locate executable nagfor
      customize FujitsuFCompiler
      Could not locate executable frt
      don't know how to compile Fortran code on platform 'posix'
      warning: build_ext: f77_compiler=None is not available.
      
      building 'ellc.ellc_f' extension
      error: extension 'ellc.ellc_f' has Fortran sources but no Fortran compiler found
      
      ########### EXT COMPILER OPTIMIZATION ###########
      Platform      :
        Architecture: x64
        Compiler    : gcc
      
      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : -msse -msse2 -msse3
        Extra checks: none
      
      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      CCompilerOpt.cache_flush[804] : write cache to path -> /tmp/pip-install-58u1sh9_/ellc_ce35a470ee0248cfa159333057a4c85f/build/temp.linux-x86_64-cpython-38/ccompiler_opt_cache_ext.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> ellc

I have tried the solution provided (via installing through brew), but it also giving some error

**Comment by MNGuenther** [comment]
Hi @sam687 thanks for reaching out. As this is not an allesfitter issue, I recommend raising this issue on ellc's page (https://github.com/pmaxted/ellc/issues) instead. 

(@wangxianyu7, not to put any monkeys on your back, but please feel free to chime in if you spot any easy solution.)

**Comment by sam687** [comment]
ok. Thank you.

**Comment by wangxianyu7** [comment]
@sam687  To install ellc, you will first need to install gfortran. You can do this by running 'apt install gfortran'.

**Comment by sam687** [comment]
@MNGuenther @wangxianyu7 Thank you. It works.

**Comment by MNGuenther** [comment]
As always, thanks so much @wangxianyu7. I will add your wisdom to the website's installation page!
