### ISSUE TITLE
Unable to apply logarithmic Limb darkening law

### ISSUE THREAD

**Issue by ganesh1076** [MNGuenther/allesfitter#65]
I am using allesfitter on a system of Eclisping Binary stars and for the same I wanted to apply the logarithmic limb darkening law for both stars to determine the limb darkening coefficient. but, I couldn't find the option in the readme or online example.

Thank you

**Comment by tdaylan** [comment]
Hi Ganesh,

Logarithmic limb darkening is not available in the default q_i parametrization. You can include
host_ld_space_X,u
b_ld_space_X,u
host_ld_law_X,log
b_ld_law_X,log

in the settings file to switch to a u_i basis and then define host_ldc_u1_X, host_ldc_u2_X, b_ldc_u1_X, and b_ldc_u2_X as usual in the params file for the two-parameter logarithmic limb darkening parameterization, where X is to be replaced with your instrument, and the two coefficients multiply the (1-mu) and mu*ln(mu) terms.

Best,
Tansu




———————————————————
Dr. Tansu Daylan
LSSTC Catalyst Fellow
Department of Astrophysical Sciences
4 Ivy Lane, Princeton University, Princeton, NJ 08544
http://www.tansudaylan.com
Fall 2023: incoming assistant professor of physics at Washington University in St. Louis

On Apr 12, 2023, at 08:45, Ganesh Pawar ***@***.***> wrote:



I am using allesfitter on a system of Eclisping Binary stars and for the same I wanted to apply the logarithmic limb darkening law for both stars. but, I couldn't find the option in the readme or online example.

Thank you

**Comment by ganesh1076** [comment]
Hi Tansu,

Thank you so much. I am able to constraint these coefficients into more realistic values :)

Regards
Ganesh

**Comment by tansudaylan** [comment]
Hi Ganesh,

Not at all. Best of luck with your research.

Best,
Tansu


———————————————————
Dr. Tansu Daylan
LSSTC Catalyst Fellow
Department of Astrophysical Sciences
4 Ivy Lane, Princeton University, Princeton, NJ 08544
http://www.tansudaylan.com
Fall 2023: incoming assistant professor of physics at Washington University in St. Louis

On Apr 20, 2023, at 10:57, Ganesh Pawar ***@***.***> wrote:



Hi Tansu,

Thank you so much. I am able to constraint these coefficients into more realistic values :)

Regards
Ganesh
