### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by martindevora** [MNGuenther/allesfitter#67]
Hello, few weeks ago you merged a pull request that I sent for allesfitter correcting a bug which was preventing allesclass being used without errors. I noticed that you haven't published a new version with the mentioned fix, could you do so please? If not, I can't use your package from pypi with the bugfix.

Regards.

**Comment by MNGuenther** [comment]
Hi @martindevora I won't push an update to pypi anytime soon, as I have several local upgrades in the works that I want to finish and thoroughly test beforehand. I would recommend you directly install your version by pulling from GitHub and/or simply making the same changes to your local files for the time being.
