### ISSUE TITLE
Question: SNR value of final fit

### ISSUE THREAD

**Issue by martindevora** [MNGuenther/allesfitter#68]
Hi,
I was wondering about what would be the appropriate value to be reported as SNR for a given planet after the fit is done with the next steps:
1 Initial out of transit estimation of noise
2 Final fit of planetary signals is done with gaussian distributions

So far I thought of using the depth significance (depth / depth uncertainty), but is there any more accurate SNR somehow computed from the allesfitter results for each signal so it can be finally reported in a scientific article?

Thank you,
Martín.

**Comment by MNGuenther** [comment]
Hi @martindevora, there is no internal computation of the SNR value in allesfitter. 

Definitions of SNR might differ in the literature, but I would generally suggest to use SNR = signal / noise = posterior median / posterior uncertainty. Of course, this assumes a Gaussian (and symmetric) posterior, but for exoplanet transit depths I think that is usually a good approximation.

**Comment by tansudaylan** [comment]
Hi Martin,

By definition, an SNR exists for a specific observable, such as the transit depth, as you mentioned. This could be obtained by dividing the posterior-median transit depth by its 1-sigma confidence interval. However, the overall performance of a model under the data is quantified by the Bayesian evidence, which takes into account the goodness of fit and the model complexity. So, if you are looking for a scalar that summarizes the model’s performance, Bayesian evidence would be what you want.

Best,
Tansu



———————————————————
Dr. Tansu Daylan
LSSTC Catalyst Fellow
Department of Astrophysical Sciences
4 Ivy Lane, Princeton University, Princeton, NJ 08544
http://www.tansudaylan.com
Fall 2023: incoming assistant professor of physics at Washington University in St. Louis

On May 4, 2023, at 08:11, martindevora ***@***.***> wrote:



Hi,
I was wondering about what would be the appropriate value to be reported as SNR for a given planet after the fit is done with the next steps:
1 Initial out of transit estimation
2 Final fit of planetary signals is done with gaussian distributions

So far I thought of using the depth significance (depth / depth uncertainty), but is there any more accurate SNR somehow computed from the allesfitter results for each signal so it can be finally reported in a scientific article?

Thank you,
Martín.
