### ISSUE TITLE
Phase Curves tutorial

### ISSUE THREAD

**Issue by ldoyle4** [MNGuenther/allesfitter#69]
Hi Max,

I was wondering if you have the phase curves tutorial? On the Allesfittter website, it says it is on GitHub but there is no folder for it!

Thanks,
Lauren

**Comment by MNGuenther** [comment]
Hi @ldoyle4 
You can find that tutorial in the "paper" folder on GitHub: https://github.com/MNGuenther/allesfitter/tree/master/paper/WASP-18 
Hope this helps!
