### ISSUE TITLE
Star spots tutorial not available 

### ISSUE THREAD

**Issue by mdredyanahmed** [MNGuenther/allesfitter#72]
The star spots tutorial which is mentioned in the allesfitter website is not found in github. I need it urgently. Can you make it public in github?

**Comment by MNGuenther** [comment]
Hi @mdredyanahmed - the tutorial was shifted into the paper in the end; please see the corresponding chapter in the paper and https://github.com/MNGuenther/allesfitter/tree/master/paper/GJ_1243
