### ISSUE TITLE
Find something wrong on the traceback for Spots_number when fitting the EBs.

### ISSUE THREAD

**Issue by Xiongjianping0417** [MNGuenther/allesfitter#9]
![image](https://user-images.githubusercontent.com/48785729/82733820-3a080900-9d49-11ea-9e24-9d25662402de.png)
I have used the program to fit the EBs, but there were always something wrong on the traceback for Spots_number(I have put the information in the attachment.) Thank you very much.

**Comment by MNGuenther** [comment]
Thanks! This should now be fixed in all versions >= `1.1.1c` (on PyPi and GitHub). Please let us know if there are any other issues :)
